# Generated by Django 2.2.7 on 2019-11-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='position_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
