# Generated by Django 2.2.7 on 2019-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_food', '0002_vendor_position_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('radius', models.IntegerField()),
            ],
        ),
    ]
