# Generated by Django 2.2.7 on 2019-11-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_food', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='loc',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='find_food.Location'),
            preserve_default=False,
        ),
    ]
